//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from coll.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="collParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IcollListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="collParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] collParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="collParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] collParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="collParser.format"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormat([NotNull] collParser.FormatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="collParser.format"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormat([NotNull] collParser.FormatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="collParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint([NotNull] collParser.ConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="collParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint([NotNull] collParser.ConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="collParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] collParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="collParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] collParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="collParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet([NotNull] collParser.SetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="collParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet([NotNull] collParser.SetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="collParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] collParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="collParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] collParser.ListContext context);
}
